#!/bin/bash
#   lista diretorios
#
#   Julio Cezar Neves
#


case "$#" in
    0) Dir=${PWD}
       Opc="d"
       ;;
    1) if  [ $1 = '-l' ]
       then
           Opc="ld"
           Dir=$PWD
       else
           Opc="d"
           Dir=$1
       fi
       ;;
    *) if  [ $1 = '-l' ]
       then
           Opc="ld"
           Dir=
           shift
           for i in $*
           do
               if  [ ! -d "$i" ]
               then
                   continue
               fi
               Dir="${Dir}${i} "
           done
       else
           Opc="d"
           Dir=
           for i in $*
           do
               if  [ ! -d "$i" ]
               then
                   continue
               fi
               Dir="${Dir}${i} "
           done
       fi
       ;;
esac
# echo $Dir ; read a
for D in $Dir
do
    echo "${D}:"
    ls -a $D |
    {
    while read Arq
    do
        [ "$Arq" = "." -o "(" "$Arq" = ".." ")" ] && continue
        if  [ -d "$D/$Arq" ] 
        then
            echo "  \c"
            ls "-$Opc" "$D/$Arq"
        fi
    done # 2>/dev/null
    }
#    a=$?
#    [ "$a" -ne 0 ] && echo "l: $a too many parameters";exit $a
done


exit